[package]
name = "CCweb"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
uuid = { version = "1.2", features = ["v4"] }
bcrypt = "0.10"
axum = "0.7.5"
